name: client_ci

on:
  push:
    branches: [ master ]
    paths:
    - client/
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: vxavictor513
          password: ${{ secrets.GHCR_TOKEN }}
          logout: true  
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Create image
        run: pack build client --buildpack gcr.io/paketo-buildpacks/nginx
        working-directory: client/
      - name: Push image
        run: |
          docker tag client:latest ghcr.io/vxavictor513/client:latest
          docker push ghcr.io/vxavictor513/client:latest
