name: resourceserver_ci

on:
  push:
    branches: [ master ]
    paths:
      - resourceserver/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: gradle bootBuildImage
        run: ./gradlew bootBuildImage --publishImage -PdockerPublishRegistryPassword=${{ secrets.GHCR_TOKEN }}
        working-directory: resourceserver
  deploy:
    runs-on: ubuntu-latest
    needs: buildAndPush
    steps:
      - uses: actions/checkout@v2
#       - name: Helm tool installer
#         uses: Azure/setup-helm@v1
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      # KUBE_CONFIG_DATA is a base64-encoded kubeconfig file with credentials for Kubernetes to access the cluster. You can get it by running the following command:
      # cat $HOME/.kube/config | base64
      - name: Helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: helm upgrade -i resourceserver ./resourceserver/helm
